#!/usr/bin/env bash
set -euo pipefail

out_file="${1:-../handoff_bundle_phase10-11.md}"

files=(
  "REFACTOR_LOG.md"
  "docs/ai/UPLOAD_BUNDLE_MASTER.md"
  "docs/ai/UPLOAD_BUNDLE_PHASE10-11.md"
  "docs/ai/UPLOAD_BUNDLE_PHASE11-CODE.md"
  "docs/ai/review_packet_bundle_phase10-11_docs.md"
  "docs/ai/review_packet_bundle_phase11_code.md"
)

{
  echo "# 3DCityMapper Handoff Bundle (Markdown Only)"
  echo
  echo "Generated by tools/make_handoff_bundle_md_only.sh"
  echo
  for f in "${files[@]}"; do
    if [[ -f "$f" ]]; then
      echo "---"
      echo
      echo "## FILE: $f"
      echo
      cat "$f"
      echo
    else
      echo "---"
      echo
      echo "## FILE: $f"
      echo
      echo "(missing in current checkout)"
      echo
    fi
  done
} > "$out_file"

echo "handoff_markdown=$out_file"
